// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IElementFields {
  /** Name */
  name: string;

  /** Slug */
  slug: string;

  /** Description */
  description?: Document | undefined;

  /** Image */
  image: Asset;

  /** Caption */
  caption: string;

  /** Order */
  order: number;
}

/** Theory Elements */

export interface IElement extends Entry<IElementFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'element';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IHeaderFields {
  /** Title */
  title: string;

  /** Slug */
  slug: string;

  /** Subtitle */
  subtitle?: string | undefined;

  /** Text */
  text: Document;

  /** Image */
  image?: Asset | undefined;
}

/** Page headers containing a hero image */

export interface IHeader extends Entry<IHeaderFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'header';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IQualificationFields {
  /** Description */
  description: string;

  /** Link */
  link?: string | undefined;

  /** Type */
  type: 'certification' | 'education';
}

/** Education and Certifications */

export interface IQualification extends Entry<IQualificationFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'qualification';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IQuestionFields {
  /** Question */
  question: string;

  /** Slug */
  slug: string;

  /** Answer */
  answer?: Document | undefined;

  /** Order */
  order: number;
}

/** Frequently Asked Questions */

export interface IQuestion extends Entry<IQuestionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'question';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IReviewFields {
  /** Text */
  text: string;

  /** Name */
  name: string;
}

export interface IReview extends Entry<IReviewFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'review';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IServiceFields {
  /** Name */
  name: string;

  /** Slug */
  slug: string;

  /** Description */
  description: Document;

  /** Image */
  image: Asset;

  /** Caption */
  caption: string;
}

/** Services offered */

export interface IService extends Entry<IServiceFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'service';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE =
  | 'element'
  | 'header'
  | 'qualification'
  | 'question'
  | 'review'
  | 'service';

export type IEntry =
  | IElement
  | IHeader
  | IQualification
  | IQuestion
  | IReview
  | IService;

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
